-- =========================================================================
-- Supabase PostgreSQL Migration: MSI MOBILE.COM Complete Schema, RLS & Atomic Order RPC
-- Migration Date: 2026-09-01
-- =========================================================================

-- Enable UUID extension
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

-- =========================================================================
-- 1. PROFILES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID PRIMARY KEY REFERENCES auth.users(id) ON DELETE CASCADE,
  email TEXT,
  full_name TEXT,
  avatar_url TEXT,
  phone TEXT,
  address TEXT,
  district TEXT,
  role TEXT NOT NULL DEFAULT 'customer' CHECK (role IN ('admin', 'customer', 'staff')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 2. CATEGORIES TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.categories (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL UNIQUE,
  slug TEXT NOT NULL UNIQUE,
  icon TEXT,
  description TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 3. PRODUCTS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.products (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  slug TEXT NOT NULL UNIQUE,
  brand TEXT NOT NULL,
  category_id BIGINT REFERENCES public.categories(id) ON DELETE SET NULL,
  category TEXT,
  price NUMERIC(12, 2) NOT NULL CHECK (price >= 0),
  discount_price NUMERIC(12, 2) CHECK (discount_price IS NULL OR discount_price >= 0),
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  specs TEXT,
  description TEXT,
  image_url TEXT,
  images JSONB DEFAULT '[]'::jsonb,
  rating NUMERIC(3, 2) DEFAULT 5.0,
  reviews_count INTEGER DEFAULT 0,
  is_featured BOOLEAN DEFAULT false,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 4. PRODUCT VARIATIONS TABLE (Color, Storage, SKU & Variation Stock)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.product_variations (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  color TEXT,
  color_code TEXT,
  storage TEXT,
  sku TEXT UNIQUE,
  price NUMERIC(12, 2) CHECK (price IS NULL OR price >= 0),
  discount_price NUMERIC(12, 2) CHECK (discount_price IS NULL OR discount_price >= 0),
  stock INTEGER NOT NULL DEFAULT 0 CHECK (stock >= 0),
  image_url TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 5. REVIEWS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  user_name TEXT NOT NULL,
  rating INTEGER NOT NULL CHECK (rating >= 1 AND rating <= 5),
  comment TEXT NOT NULL,
  is_approved BOOLEAN DEFAULT true,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 6. COUPONS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.coupons (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL UNIQUE,
  discount_type TEXT NOT NULL CHECK (discount_type IN ('percentage', 'fixed')),
  discount_value NUMERIC(12, 2) NOT NULL CHECK (discount_value > 0),
  min_order_amount NUMERIC(12, 2) NOT NULL DEFAULT 0,
  max_discount_amount NUMERIC(12, 2),
  is_active BOOLEAN NOT NULL DEFAULT true,
  expires_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 7. CART ITEMS TABLE (Persistent Multi-Device Cart for Logged-In Users)
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.cart_items (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id BIGINT NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  variation_id BIGINT REFERENCES public.product_variations(id) ON DELETE SET NULL,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, product_id, variation_id)
);

-- =========================================================================
-- 8. ORDERS TABLE
-- =========================================================================
CREATE TABLE IF NOT EXISTS public.orders (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id UUID REFERENCES public.profiles(id) ON DELETE SET NULL,
  customer_name TEXT,
  customer_email TEXT,
  customer_phone TEXT,
  shipping_address JSONB,
  items JSONB NOT NULL DEFAULT '[]'::jsonb,
  total_amount NUMERIC(12, 2) NOT NULL DEFAULT 0 CHECK (total_amount >= 0),
  payment_method TEXT DEFAULT 'COD',
  payment_status TEXT DEFAULT 'unpaid' CHECK (payment_status IN ('unpaid', 'paid', 'refunded')),
  status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending', 'confirmed', 'processing', 'shipped', 'out_for_delivery', 'delivered', 'cancelled', 'returned')),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- =========================================================================
-- 9. PERFORMANCE INDEXES
-- =========================================================================
CREATE INDEX IF NOT EXISTS idx_products_category_id ON public.products(category_id);
CREATE INDEX IF NOT EXISTS idx_products_brand ON public.products(brand);
CREATE INDEX IF NOT EXISTS idx_products_price ON public.products(price);
CREATE INDEX IF NOT EXISTS idx_products_slug ON public.products(slug);
CREATE INDEX IF NOT EXISTS idx_product_variations_product_id ON public.product_variations(product_id);
CREATE INDEX IF NOT EXISTS idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX IF NOT EXISTS idx_cart_items_user_id ON public.cart_items(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_user_id ON public.orders(user_id);
CREATE INDEX IF NOT EXISTS idx_orders_status ON public.orders(status);
CREATE INDEX IF NOT EXISTS idx_coupons_code ON public.coupons(code);

-- =========================================================================
-- 10. HELPER FUNCTION: is_admin() (SECURITY DEFINER to prevent RLS recursion)
-- =========================================================================
CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS BOOLEAN
LANGUAGE sql
SECURITY DEFINER
SET search_path = public
STABLE
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE id = auth.uid() AND role = 'admin'
  );
$$;

-- =========================================================================
-- 11. TRIGGER: AUTOMATIC PROFILE ON AUTH SIGNUP (handle_new_user)
-- =========================================================================
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  INSERT INTO public.profiles (id, email, full_name, role)
  VALUES (
    NEW.id,
    NEW.email,
    COALESCE(NEW.raw_user_meta_data->>'full_name', split_part(NEW.email, '@', 1)),
    'customer'
  )
  ON CONFLICT (id) DO UPDATE
  SET email = EXCLUDED.email,
      full_name = EXCLUDED.full_name;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =========================================================================
-- 12. TRIGGER: PROTECT ROLE COLUMN FROM PRIVILEGE ESCALATION
-- =========================================================================
CREATE OR REPLACE FUNCTION public.protect_profile_role()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
  IF NEW.role IS DISTINCT FROM OLD.role THEN
    IF NOT public.is_admin() THEN
      RAISE EXCEPTION 'Unauthorized: Only an Administrator can change user roles.';
    END IF;
  END IF;
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_protect_profile_role ON public.profiles;
CREATE TRIGGER trg_protect_profile_role
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.protect_profile_role();

-- =========================================================================
-- 13. ATOMIC ORDER CREATION & ROW-LOCKED STOCK DECREMENT RPC
-- =========================================================================
CREATE OR REPLACE FUNCTION public.create_order_atomic(
  p_user_id UUID,
  p_customer_name TEXT,
  p_customer_email TEXT,
  p_customer_phone TEXT,
  p_shipping_address JSONB,
  p_items JSONB,
  p_payment_method TEXT,
  p_coupon_code TEXT DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_item JSONB;
  v_prod RECORD;
  v_var RECORD;
  v_subtotal NUMERIC(12, 2) := 0;
  v_discount NUMERIC(12, 2) := 0;
  v_shipping NUMERIC(12, 2) := 120;
  v_total NUMERIC(12, 2) := 0;
  v_order_items JSONB := '[]'::jsonb;
  v_item_price NUMERIC(12, 2);
  v_item_name TEXT;
  v_item_img TEXT;
  v_qty INT;
  v_coupon RECORD;
  v_order_id BIGINT;
BEGIN
  IF jsonb_array_length(p_items) = 0 THEN
    RAISE EXCEPTION 'Cannot create an empty order.';
  END IF;

  -- 1. Loop through items with row-level locks (FOR UPDATE)
  FOR v_item IN SELECT * FROM jsonb_array_elements(p_items)
  LOOP
    v_qty := (v_item->>'quantity')::INT;
    IF v_qty <= 0 THEN
      RAISE EXCEPTION 'Invalid item quantity: %', v_qty;
    END IF;

    IF (v_item->>'variation_id') IS NOT NULL AND (v_item->>'variation_id') != 'null' AND (v_item->>'variation_id') != '' THEN
      -- Lock variation row
      SELECT * INTO v_var
      FROM public.product_variations
      WHERE id = (v_item->>'variation_id')::BIGINT
      FOR UPDATE;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'Product variation not found (id: %)', v_item->>'variation_id';
      END IF;

      -- Check variation stock
      IF v_var.stock < v_qty THEN
        RAISE EXCEPTION 'Insufficient stock for % (%). Available: %, Requested: %',
          v_var.color, v_var.storage, v_var.stock, v_qty;
      END IF;

      -- Fetch parent product
      SELECT * INTO v_prod FROM public.products WHERE id = v_var.product_id FOR UPDATE;
      
      v_item_price := COALESCE(v_var.price, v_prod.price);
      v_item_name := v_prod.name || ' (' || COALESCE(v_var.color, '') || ' ' || COALESCE(v_var.storage, '') || ')';
      v_item_img := COALESCE(v_var.image_url, v_prod.image_url);

      -- Decrement variation stock atomically
      UPDATE public.product_variations
      SET stock = stock - v_qty
      WHERE id = v_var.id;

      -- Also decrement parent product aggregate stock
      UPDATE public.products
      SET stock = GREATEST(0, stock - v_qty)
      WHERE id = v_prod.id;

    ELSE
      -- Lock base product row
      SELECT * INTO v_prod
      FROM public.products
      WHERE id = (v_item->>'product_id')::BIGINT
      FOR UPDATE;

      IF NOT FOUND THEN
        RAISE EXCEPTION 'Product not found (id: %)', v_item->>'product_id';
      END IF;

      -- Check product stock
      IF v_prod.stock < v_qty THEN
        RAISE EXCEPTION 'Insufficient stock for "%". Available: %, Requested: %',
          v_prod.name, v_prod.stock, v_qty;
      END IF;

      v_item_price := v_prod.price;
      v_item_name := v_prod.name;
      v_item_img := v_prod.image_url;

      -- Decrement product stock atomically
      UPDATE public.products
      SET stock = stock - v_qty
      WHERE id = v_prod.id;
    END IF;

    -- Calculate line subtotal
    v_subtotal := v_subtotal + (v_item_price * v_qty);

    -- Build snapshot of order item
    v_order_items := v_order_items || jsonb_build_object(
      'product_id', v_prod.id,
      'variation_id', CASE WHEN v_var.id IS NOT NULL THEN v_var.id ELSE NULL END,
      'name', v_item_name,
      'price', v_item_price,
      'quantity', v_qty,
      'image_url', v_item_img
    );
  END LOOP;

  -- 2. Server-side coupon verification
  IF p_coupon_code IS NOT NULL AND p_coupon_code <> '' THEN
    SELECT * INTO v_coupon
    FROM public.coupons
    WHERE UPPER(code) = UPPER(p_coupon_code)
      AND is_active = true
      AND (expires_at IS NULL OR expires_at > NOW());

    IF FOUND THEN
      IF v_subtotal >= v_coupon.min_order_amount THEN
        IF v_coupon.discount_type = 'percentage' THEN
          v_discount := (v_subtotal * v_coupon.discount_value) / 100;
          IF v_coupon.max_discount_amount IS NOT NULL THEN
            v_discount := LEAST(v_discount, v_coupon.max_discount_amount);
          END IF;
        ELSE
          v_discount := LEAST(v_subtotal, v_coupon.discount_value);
        END IF;
      END IF;
    END IF;
  END IF;

  -- Free delivery for orders above ৳50,000
  IF v_subtotal > 50000 THEN
    v_shipping := 0;
  END IF;

  v_total := GREATEST(0, (v_subtotal - v_discount) + v_shipping);

  -- 3. Insert into orders table
  INSERT INTO public.orders (
    user_id,
    customer_name,
    customer_email,
    customer_phone,
    shipping_address,
    items,
    total_amount,
    payment_method,
    payment_status,
    status
  ) VALUES (
    p_user_id,
    p_customer_name,
    p_customer_email,
    p_customer_phone,
    p_shipping_address,
    v_order_items,
    v_total,
    p_payment_method,
    'unpaid',
    'pending'
  ) RETURNING id INTO v_order_id;

  -- 4. Clear cart items for user if logged in
  IF p_user_id IS NOT NULL THEN
    DELETE FROM public.cart_items WHERE user_id = p_user_id;
  END IF;

  -- 5. Return complete order summary
  RETURN jsonb_build_object(
    'success', true,
    'order_id', v_order_id,
    'subtotal', v_subtotal,
    'discount_amount', v_discount,
    'shipping_charge', v_shipping,
    'total_amount', v_total,
    'payment_method', p_payment_method,
    'status', 'pending'
  );
END;
$$;

-- =========================================================
-- 14. ROW LEVEL SECURITY (RLS) POLICIES
-- =========================================================

-- Profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Profiles are readable by authenticated users" ON public.profiles;
CREATE POLICY "Profiles are readable by authenticated users" ON public.profiles FOR SELECT TO authenticated USING (true);
DROP POLICY IF EXISTS "Users can update own profile" ON public.profiles;
CREATE POLICY "Users can update own profile" ON public.profiles FOR UPDATE TO authenticated USING (auth.uid() = id) WITH CHECK (auth.uid() = id);
DROP POLICY IF EXISTS "Admins have full access on profiles" ON public.profiles;
CREATE POLICY "Admins have full access on profiles" ON public.profiles FOR ALL TO authenticated USING (public.is_admin());

-- Categories
ALTER TABLE public.categories ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view categories" ON public.categories;
CREATE POLICY "Public can view categories" ON public.categories FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can insert categories" ON public.categories;
CREATE POLICY "Admins can insert categories" ON public.categories FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admins can update categories" ON public.categories;
CREATE POLICY "Admins can update categories" ON public.categories FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admins can delete categories" ON public.categories;
CREATE POLICY "Admins can delete categories" ON public.categories FOR DELETE TO authenticated USING (public.is_admin());

-- Products
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view products" ON public.products;
CREATE POLICY "Public can view products" ON public.products FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can insert products" ON public.products;
CREATE POLICY "Admins can insert products" ON public.products FOR INSERT TO authenticated WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admins can update products" ON public.products;
CREATE POLICY "Admins can update products" ON public.products FOR UPDATE TO authenticated USING (public.is_admin()) WITH CHECK (public.is_admin());
DROP POLICY IF EXISTS "Admins can delete products" ON public.products;
CREATE POLICY "Admins can delete products" ON public.products FOR DELETE TO authenticated USING (public.is_admin());

-- Product Variations
ALTER TABLE public.product_variations ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view product variations" ON public.product_variations;
CREATE POLICY "Public can view product variations" ON public.product_variations FOR SELECT TO anon, authenticated USING (true);
DROP POLICY IF EXISTS "Admins can manage product variations" ON public.product_variations;
CREATE POLICY "Admins can manage product variations" ON public.product_variations FOR ALL TO authenticated USING (public.is_admin());

-- Reviews
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view approved reviews" ON public.reviews;
CREATE POLICY "Public can view approved reviews" ON public.reviews FOR SELECT TO anon, authenticated USING (is_approved = true OR public.is_admin());
DROP POLICY IF EXISTS "Authenticated users can post reviews" ON public.reviews;
CREATE POLICY "Authenticated users can post reviews" ON public.reviews FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins can manage reviews" ON public.reviews;
CREATE POLICY "Admins can manage reviews" ON public.reviews FOR ALL TO authenticated USING (public.is_admin());

-- Coupons
ALTER TABLE public.coupons ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can view active coupons" ON public.coupons;
CREATE POLICY "Public can view active coupons" ON public.coupons FOR SELECT TO anon, authenticated USING (is_active = true);
DROP POLICY IF EXISTS "Admins can manage coupons" ON public.coupons;
CREATE POLICY "Admins can manage coupons" ON public.coupons FOR ALL TO authenticated USING (public.is_admin());

-- Cart Items
ALTER TABLE public.cart_items ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view and manage own cart" ON public.cart_items;
CREATE POLICY "Users can view and manage own cart" ON public.cart_items FOR ALL TO authenticated USING (auth.uid() = user_id) WITH CHECK (auth.uid() = user_id);

-- Orders
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Users can view own orders or admins can view all" ON public.orders;
CREATE POLICY "Users can view own orders or admins can view all" ON public.orders FOR SELECT TO authenticated USING (auth.uid() = user_id OR public.is_admin());
DROP POLICY IF EXISTS "Users can insert own orders" ON public.orders;
CREATE POLICY "Users can insert own orders" ON public.orders FOR INSERT TO authenticated WITH CHECK (auth.uid() = user_id);
DROP POLICY IF EXISTS "Admins can update and manage all orders" ON public.orders;
CREATE POLICY "Admins can update and manage all orders" ON public.orders FOR ALL TO authenticated USING (public.is_admin());

-- =========================================================
-- 15. SEED DEFAULT COUPONS & CATEGORIES
-- =========================================================
INSERT INTO public.coupons (code, discount_type, discount_value, min_order_amount, max_discount_amount) VALUES
  ('MSIFIRST', 'percentage', 10, 1000, 2000),
  ('EID2026', 'fixed', 1000, 15000, 1000)
ON CONFLICT (code) DO NOTHING;

INSERT INTO public.categories (name, slug, icon, description) VALUES
  ('Smartphones', 'smartphones', 'Smartphone', 'Official flagship & mid-range smartphones'),
  ('Laptops', 'laptops', 'Laptop', 'Gaming laptops & creator workstations'),
  ('Tablets', 'tablets', 'Tablet', 'iPads & Android media tablets'),
  ('Smart Watches', 'smart-watches', 'Watch', 'Fitness trackers & premium smartwatches'),
  ('Earbuds', 'earbuds', 'Headphones', 'True wireless stereo earbuds & ANC pods'),
  ('Headphones', 'headphones', 'Headset', 'Over-ear studio & noise cancelling headphones'),
  ('Speakers', 'speakers', 'Volume2', 'Portable bluetooth & home audio speakers'),
  ('Chargers & Power Banks', 'chargers', 'Zap', 'GaN fast chargers, power banks & cables'),
  ('Gaming', 'gaming', 'Gamepad2', 'Gaming gear, consoles & accessories'),
  ('Cameras', 'cameras', 'Camera', 'Action cameras, vlogging gear & gimbals')
ON CONFLICT (slug) DO NOTHING;
